import { chromium } from '@playwright/test';
import { existsSync, mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
const candidates=['C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files/Microsoft/Edge/Application/msedge.exe'];
const executablePath=candidates.find(existsSync);
const browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.RAYAN_TEST_URL||'http://localhost:5173');
await page.getByRole('button',{name:'Preview dashboard'}).click();
await page.getByRole('heading',{name:'Business overview.'}).waitFor();
await page.getByRole('button',{name:'New project'}).click();
let dialog=page.getByRole('dialog');
await dialog.getByLabel('Project name').fill('Atlas client portal');
await dialog.getByLabel('Contract ID').fill('RTS-QA-001');
await dialog.getByLabel('Client / company').fill('Atlas Trading');

await dialog.getByLabel('Client contact').fill('+93 700 123 456');
await dialog.getByLabel('Repository link').fill('https://github.com/example/atlas');
await dialog.getByLabel('Deployment link').fill('https://atlas.example.com');
await dialog.getByLabel('Project details',{exact:true}).fill('A customer portal with project tracking.');
await dialog.getByLabel('Paid money (AFN)').fill('35000');
await dialog.getByLabel('Remaining money (AFN)').fill('65000');
assert.match(await dialog.locator('#contract-total').innerText(),/100,000/);
assert.equal(await dialog.getByRole('checkbox').count(),0);

await dialog.getByRole('button',{name:'Create project'}).click();
await page.getByRole('heading',{name:'Business overview.'}).waitFor();
assert.match(await page.locator('.metric.featured').innerText(),/35,000/);

await page.getByRole('button',{name:'Add investment',exact:true}).click();
dialog=page.getByRole('dialog');
await dialog.getByLabel('Partner',{exact:true}).selectOption('Khoshal Amin');
await dialog.getByLabel('Investment amount (AFN)').fill('20000');
await dialog.getByLabel('Note (optional)').fill('Startup capital');
await dialog.getByRole('button',{name:'Save investment'}).click();
await page.getByRole('heading',{name:'Business overview.'}).waitFor();
assert.match(await page.locator('.metric.featured').innerText(),/55,000/);
await page.getByRole('link',{name:'Investments',exact:true}).click();
await page.getByRole('cell',{name:'Startup capital'}).waitFor();
assert.match(await page.locator('.metrics-grid .metric').first().innerText(),/20,000/);
await page.getByRole('link',{name:'Expenses',exact:true}).click();
await page.getByRole('button',{name:'Add expense'}).click();
dialog=page.getByRole('dialog');
await dialog.getByLabel('Reason').fill('Office internet');
await dialog.getByLabel('Amount (AFN)').fill('10000');
await dialog.getByRole('button',{name:'Save expense'}).click();
await page.getByText('Office internet',{exact:true}).waitFor();
await page.getByRole('link',{name:'Partner payments',exact:true}).click();
assert.equal(await page.locator('.partner-card').count(),4);
await page.locator('.partner-card').first().getByRole('button',{name:'Pay partner'}).click();
dialog=page.getByRole('dialog');
await dialog.getByLabel('Amount (AFN)').fill('5000');
await dialog.getByRole('button',{name:'Record payout'}).click();
await page.locator('.partner-card').first().getByText('AFN 5,000.00',{exact:true}).first().waitFor();
await page.getByRole('link',{name:'Projects',exact:true}).click();


await page.getByRole('button',{name:'Edit',exact:true}).click();
dialog=page.getByRole('dialog');
assert.equal(await dialog.getByLabel('Project name').inputValue(),'Atlas client portal');
assert.equal(await dialog.getByLabel('Client contact').inputValue(),'+93 700 123 456');
await dialog.getByLabel('Project details',{exact:true}).fill('Updated scope and delivery notes.');
await dialog.getByRole('button',{name:'Save changes',exact:true}).click();
await page.getByRole('button',{name:'Details',exact:true}).click();
dialog=page.getByRole('dialog');
await dialog.getByText('+93 700 123 456',{exact:true}).waitFor();
assert.equal(await dialog.getByRole('link',{name:'Open repository'}).getAttribute('href'),'https://github.com/example/atlas');
assert.equal(await dialog.getByRole('link',{name:'Open deployment'}).getAttribute('href'),'https://atlas.example.com/');
await dialog.getByText('Updated scope and delivery notes.',{exact:true}).waitFor();
await dialog.getByRole('button',{name:'Close',exact:true}).first().click();
await page.locator('tbody').getByRole('button',{name:'Done',exact:true}).click();
dialog=page.getByRole('dialog');
await dialog.getByRole('button',{name:'Mark as done'}).click();
await page.locator('tr.project-row.done').waitFor();
await page.getByRole('link',{name:'Subscriptions',exact:true}).click();
assert.equal(await page.locator('tbody tr').count(),2);
await page.getByRole('link',{name:'Remaining payments',exact:true}).click();
assert.match(await page.locator('.data-panel').first().innerText(),/65,000/);
await page.getByRole('button',{name:'Record payment'}).first().click();
dialog=page.getByRole('dialog');
await dialog.getByRole('spinbutton').fill('65001');
await dialog.getByRole('button',{name:'Record payment'}).click();
await dialog.getByText('Payment exceeds the outstanding balance.').waitFor();
await dialog.getByRole('spinbutton').fill('65000');
await dialog.getByRole('button',{name:'Record payment'}).click();
await page.getByText('No outstanding balances.').waitFor();
await page.getByRole('link',{name:'Overview',exact:true}).click();
assert.match(await page.locator('.metric.featured').innerText(),/105,000/);
mkdirSync('artifacts/qa',{recursive:true});
await page.screenshot({path:'artifacts/qa/dashboard-desktop.png',fullPage:true});
await page.getByRole('link',{name:'Partner payments',exact:true}).click();
await page.screenshot({path:'artifacts/qa/partners-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'artifacts/qa/partners-mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Mobile layout must not overflow horizontally');
await page.getByRole('link',{name:'Projects',exact:true}).click();
await page.getByRole('button',{name:'New project'}).click();
await page.screenshot({path:'artifacts/qa/project-form-mobile.png',fullPage:true});
await page.getByRole('button',{name:'Cancel',exact:true}).click();
assert.deepEqual(errors,[]);
console.log('PASS: prefilled project editing and saved notes; manual paid and remaining amounts, project contact/details/links, investments and history, expense, four partner cards, capped payouts, completion, subscription, overpayment rejection, final receipt, desktop and mobile layouts; no browser runtime errors.');
await browser.close();
